apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app-green
  labels:
    app: spring-app
    color: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-app
      color: green
  template:
    metadata:
      labels:
        app: spring-app
        color: green
    spec:
      containers:
        - name: spring-app
          # Note the :v2 tag here
          image: 762102778335.dkr.ecr.us-east-1.amazonaws.com/blue-green-demo:v2
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v2"
            - name: APP_COLOR
              value: "green"