apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
spec:
  type: LoadBalancer
  selector:
    app: spring-app
    color: green   # <--- Traffic is going to BLUE right now
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080